version: 0.19.{build}

image:
  - Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.1"
      PYTHON_ARCH: "64"

stack: python %PYTHON_VERSION%

install:
  - cmd: git submodule update --init --recursive
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts\;%PATH%
  - cmd: python.exe --version
  - cmd: pip.exe --version
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: pip.exe install sphinx

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPE=Release -G "Visual Studio 16 2019" -A x64 ..
  - cmd: cmake --build . --config Release

after_build:
  - cmd: 7z a worldengine.zip %APPVEYOR_BUILD_FOLDER%\build\bin\worldengine.exe %APPVEYOR_BUILD_FOLDER%\build\bin\*.dll %APPVEYOR_BUILD_FOLDER%\build\lib\*

artifacts:
  - path: build\worldengine.zip
    name: WorldEngine

test_script:
  - cmd: cd bin
  - cmd: worldengine-test.exe
  - cmd: cd ..
