#pragma once

namespace WorldEngine
{

enum class BiomeGroup
{
   BOREAL_FOREST,
   COOL_TEMPERATE_FOREST,
   WARM_TEMPERATE_FOREST,
   TROPICAL_DRY_FOREST_GROUP,
   TUNDRA,
   ICELAND,
   JUNGLE,
   SAVANNA,
   HOT_DESERT,
   COLD_PARKLANDS,
   STEPPE,
   COOL_DESERT,
   CHAPARRAL
};

enum class BiomeType
{
   OCEAN,
   SEA,
   POLAR_DESERT,
   ICE,
   SUBPOLAR_DRY_TUNDRA,
   SUBPOLAR_MOIST_TUNDRA,
   SUBPOLAR_RAIN_TUNDRA,
   BOREAL_DESERT,
   BOREAL_DRY_SCRUB,
   BOREAL_MOIST_FOREST,
   BOREAL_WET_FOREST,
   BOREAL_RAIN_FOREST,
   COOL_TEMPERATE_DESERT,
   COOL_TEMPERATE_DESERT_SCRUB,
   COOL_TEMPERATE_STEPPE,
   COOL_TEMPERATE_MOIST_FOREST,
   COOL_TEMPERATE_WET_FOREST,
   COOL_TEMPERATE_RAIN_FOREST,
   WARM_TEMPERATE_DESERT,
   WARM_TEMPERATE_DESERT_SCRUB,
   WARM_TEMPERATE_THORN_SCRUB,
   WARM_TEMPERATE_DRY_FOREST,
   WARM_TEMPERATE_MOISE_FOREST,
   WARM_TEMPERATE_WET_FOREST,
   WARM_TEMPERATE_RAIN_FOREST,
   SUBTROPICAL_DESERT,
   SUBTROPICAL_DESERT_SCRUB,
   SUBTROPICAL_THORN_WOODLAND,
   SUBTROPICAL_DRY_FOREST,
   SUBTROPICAL_MOIST_FOREST,
   SUBTROPICAL_WET_FOREST,
   SUBTROPICAL_RAIN_FOREST,
   TROPICAL_DESERT,
   TROPICAL_DESERT_SCRUB,
   TROPICAL_THORN_WOODLAND,
   TROPICAL_VERY_DRY_FOREST,
   TROPICAL_DRY_FOREST,
   TROPICAL_MOIST_FOREST,
   TROPICAL_WET_FOREST,
   TROPICAL_RAIN_FOREST
};

} // namespace WorldEngine
